{
    'name': 'Glucose Pumps Evercare',
    'version': '1.0',
    'category': 'Healthcare',
    'summary': 'Track glucose pump devices and patient assignments',
    'description': 'Track glucose pump devices and patient assignments',
    'author': 'Pretty Neat Software Ltd',
    'website': 'https://www.prettyneat.io',
    'license': 'Other proprietary',
    'development_status': 'Production/Stable',
    'depends': ['base', 'stock', 'website', 'mail'],
    'data': [
        'security/glucose_pumps_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/product_data.xml',
        'data/stock_location_data.xml',
        'data/res_partner_data.xml',
        'data/stock_lot_data.xml',
        'data/stock_quant_data.xml',
        'data/consumables_data.xml',
        'data/training_location_data.xml',
        'data/assignment_log_data.xml',
        'data/ir_cron_data.xml',
        'data/res_config_settings_data.xml',
        'views/glucose_pumps_views.xml',
        'views/res_partner_views.xml',
        'views/stock_lot_views.xml',
        'views/replace_device_wizard_views.xml',
        'views/website_templates.xml',
    ],
    'installable': True,
    'application': True,
}
